<?php

use Zend\Session\Container as Session;

// meta
echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'FireFox');

// css
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'img/icon', 'href' => $this->basePath(). '/img/homepage/icon.png'))
        ->prependStylesheet($this->basePath('css/homepage/PC.css'))
        ->prependStylesheet($this->basePath('css/homepage/design.css'));

// js
$this->headScript()
      ->appendFile($this->basePath('js/jquery-3.1.1.min.js'),
                    'text/javascript')
      ->appendFile($this->basePath('js/homepage/time/realtime.js'),
                    'text/javascript')
      ->appendFile($this->basePath('js/homepage/time/time.js'),
                   'text/javascript');
echo $this->headScript();
?>
<base href="https://bokkun.jp/" />
<header class='header'>
    <div align="left">
        <div>
            <a href="https://bokkun.jp/"><img src="cg/public/img/homepage/page-icon.gif" width="40" height="40"></a>
            <strong>
                <em>Bokkun's homepage</em> <br/>
                <div class="top" align="center">Zend Framework2による開発</div>
            </strong>
        </div>
    </div>

<!--
    今回のZend2による開発では未使用。
    メインの機能実装が終わり次第、余裕があれば再開。
      <?php
//    $ff = fopen("/img/icon.png", "r");
//    var_dump($ff);
//    $fp = fopen("/text/count.txt", "r+"); // ファイル開く
//    $count = fgets($fp, 10); // 9桁分値読み取り
//    $count++; // 値+1（カウントアップ）
//    rewind($fp); // ファイルポインタを先頭に戻す
//    fputs($fp, $count); // 値書き込み
//    fclose($fp); // ファイル閉じる
//
//    /* メッセージ出力 */
//    echo "<div align='right'><strong>" . $count . "人目の訪問者です！</strong></div>";
//    echo "<div align='right'><strong>本日" . $session['front']['count'] . "度目の訪問、ありがとうございます！</strong></div>";

//        $_SESSION = $session;
?> -->
  <div class='date' align="right"></div>
  <div class='time' align="right"></div>
</header>
