<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('bokkun\'s page
         ') ?>

    </head>
    <body>
        <div class="container">
            <?php require_once('header.phtml'); ?>
            <div class="contents">
                <?php echo $this->content; ?>
            </div>
            <?php require_once('footer.tpl'); ?>
        </div>
    </body>
</html>

